### ISSUE TITLE
monitoring/logging in the AWS instance

### ISSUE THREAD

**Issue by mgeerdsen** [wellcomecollection/goobi-infrastructure#102]
this needs to be discussed and implemented

**Comment by pollecuttn** [comment]
@mgeerdsen Is this issue still needed? If so, what is the next thing that needs to happen?

**Comment by kenoir** [comment]
Logs could be made available on https://logging.wellcomecollection.org.

See https://github.com/wellcomecollection/docs/tree/master/rfcs/022-logging for a discussion of how we do logs on the collection platform.

**Comment by mgeerdsen** [comment]
started testing with stage workernode: https://github.com/wellcomecollection/goobi-infrastructure/tree/mg/feat_add_elastic_logging

**Comment by kenoir** [comment]
See https://wellcome.slack.com/archives/C6LLC2V8Q/p1721990284363839 for discussion of how to extend this to lambda logs.

<img width="861" alt="Screenshot 2024-07-29 at 12 15 10" src="https://github.com/user-attachments/assets/569bf491-52b5-461f-b893-56f24431984b">

**Comment by mgeerdsen** [comment]
being worked on in #463
