### ISSUE TITLE
Extend lifecycle of WC Editorial bucket to six months

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/goobi-infrastructure#247]
Currently EP shoots go to AWS Glacier after 3 months.

Extending the lifecycle from 3 months to 6 months should mean we won't need to restore from Glacier in future.

See https://wellcome.slack.com/archives/C6LLC2V8Q/p1579783169033200

**Comment by aray-wellcome** [comment]
We haven't had to restore anything from the EP bucket since this ticket was made so maybe it's not really needed...

**Comment by mgeerdsen** [comment]
I think this can be closed as it does not appear to have been relevant in recent years(?).
Also this bucket is not under our control and would have to be adjusted by Wellcome.
