### ISSUE TITLE
add documentation

### ISSUE THREAD

**Issue by mgeerdsen** [wellcomecollection/goobi-infrastructure#248]
At least the following things should be documented for an easier overview and easier on-boarding

- [x] infrastructure overview
- [x] access to applications (URLs, authentication, ...)
- [x] access to AWS console for log access
- [x] deployment of applications (updates)
- [x] terraform use for updating of infra

**Comment by mgeerdsen** [comment]
deployment of harvester is not documented and handled via #257

**Comment by mgeerdsen** [comment]
re-assigning to check docs

**Comment by opaetzel** [comment]
The documentation looks good so far. What would be useful to support the system is a description of all workflow templates with information about all Goobi and TaskManager plugins involved (repo name, input and output).
