### ISSUE TITLE
get auto-scaling for 3rd party applications to production

### ISSUE THREAD

**Issue by opaetzel** [wellcomecollection/goobi-infrastructure#249]
Now that Goobi is able to put job tasks in a message queue, we need to talk about autoscaling the 3rd party applications. This is what needs to happen before we can talk about auto-scaling:

- [x] make docker-container with 3rd party applications in it
- [x] test the new queue solution locally with multiple instances of the container
- [x] infrastructure handover #234 
- [x] test the new queue solution in AWS with one instance of the container
- [x] start auto-scaling

**Comment by mgeerdsen** [comment]
Should probably test this without automatic scaling at first. This could then well be tested in the staging environment after #234

**Comment by opaetzel** [comment]
blocked by #234

**Comment by mgeerdsen** [comment]
see #325 and #326
