### ISSUE TITLE
backup data on winnipeg before decomissioning

### ISSUE THREAD

**Issue by rsehr** [wellcomecollection/goobi-infrastructure#251]
- [x] database dumps
- [x] backup metadata
- [x] check user home directories
- [x] check records that have been harvested but not correctly imported
- [x] check upload folder on ftp server
- [x] check EP hotfolder
- [x] migration logs
- [x] cron jobs

**Comment by mgeerdsen** [comment]
re-assigning to double check

**Comment by mgeerdsen** [comment]
also to check:
migration logs and various cron jobs

**Comment by mgeerdsen** [comment]
created #258 for IA items to be checked again

UKMHL directory still needs checking

**Comment by mgeerdsen** [comment]
The list of records is in #258 and the harvested XML files have also been uploaded to wellcomecollection-workflow-harvesting-results in the migrated prefix.

From our point of view the systems can be decommissioned (when users have checked their home directories)

(insert dramatic sound and "make it so" gif here)

**Comment by pollecuttn** [comment]
@mgeerdsen LOL! Great - thanks
