### ISSUE TITLE
Implement a version of the "delete identifier" plugin with the Wellcome Storage Service

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/goobi-infrastructure#252]
There are METS files with dangling entries in the mets:structMap, for example:

```xml
<mets:div ADMID="AMD" DMDID="DMDLOG_0000" ID="LOG_0000" LABEL="A brief review of the means of preserving the health of European soldiers in India" TYPE="MultipleManifestation">
  <mets:div ID="LOG_0001" LABEL="A brief review of the means of preserving the health of European soldiers in India" ORDER="1" TYPE="Monograph">
    <mets:mptr LOCTYPE="URL" xlink:href="b20415679_001.xml" />
  </mets:div>
  <mets:div ID="LOG_0002" LABEL="A brief review of the means of preserving the health of European soldiers in India" ORDER="1" TYPE="Monograph">
    <mets:mptr LOCTYPE="URL" xlink:href="b20415679_0001.xml" />
  </mets:div>
  <mets:div ID="LOG_0003" LABEL="A brief review of the means of preserving the health of European soldiers in India" ORDER="2" TYPE="Monograph">
    <mets:mptr LOCTYPE="URL" xlink:href="b20415679_002.xml" />
  </mets:div>
  <mets:div ID="LOG_0004" LABEL="A brief review of the means of preserving the health of European soldiers in India" ORDER="2" TYPE="Monograph">
    <mets:mptr LOCTYPE="URL" xlink:href="b20415679_0002.xml" />
  </mets:div>
</mets:div>
```

We'd like to be able to delete the unwanted identifiers – in this case, `_001` and `_002`.

There used to be a plugin to do this – "delete identifier" – which would open the METS file directly in the file share and delete the parts from the struct map. We need a version of this plugin that works with the Wellcome storage.

The procedure for editing a file in the Wellcome storage has a few more steps:

1. Read the existing METS file from the storage service
2. Make any edits
3. Construct a new bag that contains the edited METS file, and a `fetch.txt` pointing to the remaining files in the previous version(s) of the bag
4. Upload the new version of the bag to the storage service

**Comment by rsehr** [comment]
@alexwlchan what shall happen when we try to delete the only/last identifier? Is there a way to delete the complete bag or shall we create an update with zero files?
