### ISSUE TITLE
review IA import errors

### ISSUE THREAD

**Issue by mgeerdsen** [wellcomecollection/goobi-infrastructure#258]
The following b-numbers had not succesfully been ingested after being harvested via the IA
[missing_ia.txt](https://github.com/wellcomecollection/goobi-infrastructure/files/4214304/missing_ia.txt)

b30321062 and b30326886 where listed but could be found in Goobi.

The following were listed as suspicious and spot checking supports that, the items partly appear as an MMO but a monograph already exists in Goobi or the other way around:
[ia_suspicious.txt](https://github.com/wellcomecollection/goobi-infrastructure/files/4214356/ia_suspicious.txt)

**Comment by mgeerdsen** [comment]
for UKMHL these two are listed as suspicious:
b29733170 and b30243300
However both b-numbers can be found like this in the IA as well as in Goobi, so at a first glance they look fine.

The following b-numbers had errors during import and need the be handled:
[missing_ukmhl.txt](https://github.com/wellcomecollection/goobi-infrastructure/files/4218734/missing_ukmhl.txt)

**Comment by mgeerdsen** [comment]
the old errors have all been sorted... just the one marked "suspicious" need checking... assigning @aray-wellcome as well

**Comment by aray-wellcome** [comment]
@mgeerdsen I've gone over the items in ia_suspicious.txt and I more or less know how to fix each one of them now. But I won't need the files leftover in the suspicious folder to do so. You're free to get rid of them.
