### ISSUE TITLE
document workflows

### ISSUE THREAD

**Issue by opaetzel** [wellcomecollection/goobi-infrastructure#261]
We want to document all workflows. There is a total of 18:

- [ ] 19_century_import
- [ ] 19c_Books_MMs_Only
- [ ] Archive_digitisation_JP2
- [ ] Digitisation_on_Demand_TIFF
- [ ] Digitisation_on_Demand_JP2
- [x] Editorial_Photography
- [x] Editorial_Photography_Update
- [ ] Manuscript_ingest_TIFF
- [ ] Proquest_EEB
- [ ] Published_born_digital
- [ ] Born_digital
- [ ] Recipe_Books_TIFF
- [ ] volume_deletion_from_storage_service
- [ ] UK_MOH_Reports
- [ ] Visual_Arts_TIFF
- [ ] Visual_Arts_JP2
- [ ] Wellcome_Audio
- [ ] Wellcome_Film

**Comment by aray-wellcome** [comment]
I've consolidated the workflows. They are listed here https://github.com/wellcomecollection/goobi-infrastructure/issues/275
