### ISSUE TITLE
Domain and certificate needed for workflow-stage.wellcomecollection.org

### ISSUE THREAD

**Issue by opaetzel** [wellcomecollection/goobi-infrastructure#274]
We need a domain and a certificate for workflow-stage.wellcomecollection.org in order to get the staging environment up and running.

**Comment by kenoir** [comment]
This is available - I need the staging ALB DNS to update the CNAME for `workflow-stage.wellcomecollection.org`.

**Comment by mgeerdsen** [comment]
This is done and already in use :) Thank you
