### ISSUE TITLE
Check if the 'create derivates' task is needed in all workflows

### ISSUE THREAD

**Issue by rsehr** [wellcomecollection/goobi-infrastructure#281]
Candidates to remove it:
* 19_century_import 
* JP2_Manual_Edit_METS
* JP2_Auto_Edit_METS
* UK_MOH_Reports

**Comment by rsehr** [comment]
For 19_century_import and UK_MOH_Reports we have to change the IA download and extraction methods. Here we have to unzip the data right into the derivative folder, there is no need to use the master folder at all.
For JP2_Manual_Edit_METS and JP2_Auto_Edit_METS we have to change the zip import from s3 uploads and (if you use it) the upload via browser. As this is are areas, that are also used for tif uploads, we have to implement a distinction. Either based on file extension or on the used process template.

**Comment by rsehr** [comment]
Changes for 19_century_import and UK_MOH_Reports

task 'Import data from internet archive':
change script to: /usr/bin/java -jar /opt/digiverso/itm/bin/TaskClient.jar -itm http://workflow-stage-itm.workflow-stage/itm/service -e -gid {processid} -i {stepid} -s ${meta.CatalogIDDigital} -d ${s3_tifpath} -T {processtitle} -t IAPARSER -n iaparser

task 'Alto conversion': 
change script to: /usr/bin/java -jar /opt/digiverso/itm/bin/TaskClient.jar -itm http://workflow-stage-itm.workflow-stage/itm/service -s {tifpath} -d {processpath} -e -gid {processid} -i {stepid} -T {processtitle} -t ALTOCONVERT -n altoconvert

delete task 'Create derivates'

**Comment by rsehr** [comment]
Changes for JP2_Auto_Edit_METS and JP2_Manual_Edit_METS

- delete task 'Copy JP2 images to media folder'
- delete task 'Image conversion JPG'
- delete task '90 days delay'
- delete task 'jpeg deletion'

**Comment by rsehr** [comment]
file upload plugin must be changed to import files into the right folder when a jp2 workflow is chosen

**Comment by mgeerdsen** [comment]
Deployment to production also includes the above mentioned changes to workflow templates.

We also need to consider and prepare changes to existing processes, especially those still waiting for image upload.

**Comment by rsehr** [comment]
sql statements for the update:

# rename task 'Image upload' to 'JP2 upload'
update schritte set titel = "JP2 upload" where titel = "Image upload" and prozesseid in (select prozesseid from schritte where titel = "Copy JP2 images to media folder" and Bearbeitungsstatus = 0);

# delete task 'Copy JP2 images to media folder'
delete from schritte where titel = "Copy JP2 images to media folder" and prozesseid in (select prozesseid from schritte where titel ="JP2 upload");

# delete task 'Image conversion JPG'
delete from schritte where titel = "Image conversion JPG" and prozesseid in (select prozesseid from schritte where titel ="JP2 upload");

# delete task 'jpeg compression'
delete from schritte where titel = "jpeg compression" and prozesseid in (select prozesseid from schritte where titel ="JP2 upload");

# delete task '90 days delay'
delete from schritte where titel = "90 days delay" and prozesseid in (select prozesseid from schritte where titel ="JP2 upload");

# delete task 'jpeg deletion'
delete from schritte where titel = "jpeg deletion" and prozesseid in (select prozesseid from schritte where titel ="JP2 upload");
