### ISSUE TITLE
Change the provider string in ingest requests

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/goobi-infrastructure#298]
We've made a small change to the way we handle storage providers in the storage service.

Previously, to start an ingest, you'd make a POST request with the following body:

```
{
  ...,
  "sourceLocation": {
    "provider": {"type": "Provider", "id": "aws-s3-standard"},
    ...
  }
}
```

With the new providers, this should be changed to `"amazon-s3"`. Goobi should send the new provider string in requests to the storage service.

Part of https://github.com/wellcomecollection/platform/issues/4551

**Comment by rsehr** [comment]
@alexwlchan can we use the new name right now or do you need to prepare the storage service first?

**Comment by alexwlchan** [comment]
> can we use the new name right now or do you need to prepare the storage service first?

Right now!

The storage service will accept both names right now, but eventually I'd like to remove the code that handles the old names.

**Comment by mgeerdsen** [comment]
This was changed in Goobi and it appears it has already been deployed to production in the meantime as well.
