### ISSUE TITLE
include thumbnails in image deletion

### ISSUE THREAD

**Issue by mgeerdsen** [wellcomecollection/goobi-infrastructure#300]
Thumbnails should also be deleted by the image deletion plugin

**Comment by rsehr** [comment]
Steps to install it on production system: 

* add new plugin to docker file (see develop branch)
* add new config to bucket plugin_intranda_step_imagedeletion.xml
* change image deletion steps in mysql:
update schritte set stepPlugin = "intranda_step_imagedeletion" where stepPlugin ="WellcomeImageDeletion";
update schritte set stepPlugin = "intranda_step_imagedeletion" where stepPlugin ="JpegDeletion";
