### ISSUE TITLE
Improve handling secrets & variables in terraform

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/goobi-infrastructure#311]
Currently deploying a staging/production TF stack requires a .tfvars file which contains sensitive values.

In order to reduce the risk of exposing sensitive values and to make the terraform plan/apply easier for developers we should move to using AWS SecretsManager & SSM Parameter store to hold this variables and remove the need for a `.tfvars` file.

**Comment by mgeerdsen** [comment]
The staging environment has been deployed from [add_fargate_services](https://github.com/wellcomecollection/goobi-infrastructure/tree/add_fargate_services) and the shellserver in staging is running on fargate.

**Comment by mgeerdsen** [comment]
Production environment has now been migrated as well. Documentation has been adapted.
