### ISSUE TITLE
Create new audio workflow

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#317]
Much like the film workflow we've created from #255 we need to do the same for audio to complete the a/v work. As we are waiting for Digirati to do work on the film METS created, it makes sense to move forward on the audio side of a/v so we can have the METS ready for both. 

**1.  File types**
We need to be able to accept both .mp3 and .wav files (but we will not need Goobi to transcode them). We will also need to include transcripts (we don't have these often, but they are usually pdf) and the jpg poster images (rare but necessary to include)
**2. File upload via S3**
We would like to be able to send audio files to Goobi via the wellcomecollection-workflow-upload bucket both via S3 Goobi transfer and file upload within Goobi. However, with audio files, there will likely be anywhere from 1-6 audio files that will need to be added so it is likely not as easy setting up the Lambda to expect certain file types
**3. Docstructs** 
We need Side 1 and Side 2 as docsctruct types for labeling the items in the UV
**4. METS with file groups and usage attributes**
Just like #308 we will need audio to have the same types of file groups and usage attributes in the METS file

**Comment by rsehr** [comment]
Do you have a poster/transcript for each audio file or one for the whole process regardless how many files?

**Comment by aray-wellcome** [comment]
@rsehr That's where it gets tricky, I think. 

We have some stuff on Soundcloud we'd like to ingest that may have a poster image but probably not a transcript. 

We have some backlog audio that may have a transcript but no poster image.

The new stuff we're digitizing will likely have neither a poster image or a transcript at the moment.

**Comment by rsehr** [comment]
- [ ] allow audio files in s3 upload
- [ ] import formats into different folder
- [ ] create premis data for different formats
- [ ] create mets files for case 1: number of files is identical in all folders
- [ ] create mets file for case 2: more audio files, but only 1 transcript
- [ ] create and ingest bag
- [ ] delete files in storage service
- [ ] update files in storage service

**Comment by pollecuttn** [comment]
Awaiting new DDS before deployment to production

**Comment by aray-wellcome** [comment]
Closing this as all steps are finished on the Goobi side. If Digirati needs anything else, a new ticket will be opened.
