### ISSUE TITLE
LW exception in staging process 328030

### ISSUE THREAD

**Issue by mgeerdsen** [wellcomecollection/goobi-infrastructure#321]
process log shows the following:
> Error performing automatic LayoutWizzard saving: java.util.concurrent.ExecutionException: de.intranda.olr.exceptions.ProcessingException: java.lang.NullPointerException

**Comment by mgeerdsen** [comment]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:52.380Z TRACE 2020-08-14 16:33:52.380 [pool-8-thread-1] de.unigoettingen.sub.commons.contentlib.imagelib.AbstractImageInterpreter.canRenderWithJAI(AbstractImageInterpreter.java:516)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:52.380Z         Rendering with jai false
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:52.380Z DEBUG 2020-08-14 16:33:52.380 [pool-8-thread-1] de.unigoettingen.sub.commons.contentlib.imagelib.AbstractImageInterpreter.readImageWithImageReader(AbstractImageInterpreter.java:269)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:52.381Z         Rendering with ImageIO ImageReader
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.056Z TRACE 2020-08-14 16:33:57.056 [pool-8-thread-1] de.unigoettingen.sub.commons.contentlib.imagelib.AbstractImageInterpreter.close(AbstractImageInterpreter.java:421)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.056Z         Cleaning up ImageInterpreter
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.061Z DEBUG 2020-08-14 16:33:57.061 [pool-8-thread-1] de.intranda.olr.queue.ImageProcessingRequest.debug(ImageProcessingRequest.java:94)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.061Z         1625_b19371469_0001.tif (IMAGESAVER) status change: PROCESSING --> FAILED
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.061Z 	With message: java.lang.NullPointerException
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.061Z DEBUG 2020-08-14 16:33:57.061 [Thread-226] de.intranda.olr.LayoutManager.saveImageWithTimeout(LayoutManager.java:723)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.061Z         Request Processing IMAGESAVER on 1625_b19371469_0001.tif	 Status: FAILED returned from processing
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.063Z TRACE 2020-08-14 16:33:57.063 [pool-8-thread-1] de.intranda.olr.queue.ProcessingRequestExecutor.afterExecute(ProcessingRequestExecutor.java:58)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.063Z         Finished executing Processing IMAGESAVER on 1625_b19371469_0001.tif	 Status: FAILED
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z ERROR 2020-08-14 16:33:57.061 [Thread-226] de.intranda.olr.LayoutManager.saveImageWithTimeout(LayoutManager.java:735)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z         Execution exception for image 328030/images/master_ms_1625_b19371469_media/1625_b19371469_0001.tif
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z java.util.concurrent.ExecutionException: de.intranda.olr.exceptions.ProcessingException: java.lang.NullPointerException
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	at de.intranda.olr.LayoutManager.saveImageWithTimeout(LayoutManager.java:725) ~[LayoutWizzard-jar-with-dependencies.jar:?]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	at de.intranda.olr.LayoutManager.lambda$saveSelectedImages$1(LayoutManager.java:675) ~[LayoutWizzard-jar-with-dependencies.jar:?]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z Caused by: de.intranda.olr.exceptions.ProcessingException: java.lang.NullPointerException
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	at de.intranda.olr.queue.ImageSaverProcessingRequest.process(ImageSaverProcessingRequest.java:31) ~[LayoutWizzard-jar-with-dependencies.jar:?]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	at de.intranda.olr.LayoutManager$1.run(LayoutManager.java:495) ~[LayoutWizzard-jar-with-dependencies.jar:?]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	... 1 more
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z Caused by: java.lang.NullPointerException
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	at de.intranda.olr.pagelayout.layouter.Saver.saveImageWithDarkeningAndDPICheck(Saver.java:326) ~[LayoutWizzard-jar-with-dependencies.jar:?]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	at de.intranda.olr.pagelayout.layouter.Saver.saveInternalWithDarkening(Saver.java:295) ~[LayoutWizzard-jar-with-dependencies.jar:?]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	at de.intranda.olr.pagelayout.layouter.Saver.process(Saver.java:104) ~[LayoutWizzard-jar-with-dependencies.jar:?]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	at de.intranda.olr.queue.ImageSaverProcessingRequest.process(ImageSaverProcessingRequest.java:20) ~[LayoutWizzard-jar-with-dependencies.jar:?]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	at de.intranda.olr.LayoutManager$1.run(LayoutManager.java:495) ~[LayoutWizzard-jar-with-dependencies.jar:?]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.086Z 	... 1 more
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.087Z java.util.concurrent.ExecutionException: de.intranda.olr.exceptions.ProcessingException: java.lang.NullPointerException
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.087Z 	at de.intranda.olr.LayoutManager.saveImageWithTimeout(LayoutManager.java:725)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.087Z 	at de.intranda.olr.LayoutManager.lambda$saveSelectedImages$1(LayoutManager.java:675)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.087Z 	at java.lang.Thread.run(Thread.java:748)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.087Z Caused by: de.intranda.olr.exceptions.ProcessingException: java.lang.NullPointerException
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.087Z 	at de.intranda.olr.queue.ImageSaverProcessingRequest.process(ImageSaverProcessingRequest.java:31)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.087Z 	at de.intranda.olr.LayoutManager$1.run(LayoutManager.java:495)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.087Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.087Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.087Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.088Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.088Z 	... 1 more
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.088Z Caused by: java.lang.NullPointerException
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.088Z 	at de.intranda.olr.pagelayout.layouter.Saver.saveImageWithDarkeningAndDPICheck(Saver.java:326)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.088Z 	at de.intranda.olr.pagelayout.layouter.Saver.saveInternalWithDarkening(Saver.java:295)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.088Z 	at de.intranda.olr.pagelayout.layouter.Saver.process(Saver.java:104)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.088Z 	at de.intranda.olr.queue.ImageSaverProcessingRequest.process(ImageSaverProcessingRequest.java:20)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.088Z 	... 6 more
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.097Z DEBUG 2020-08-14 16:33:57.097 [Thread-226] de.intranda.olr.LayoutManager.finishCurrentThread(LayoutManager.java:631)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.097Z         Finishing running thread...
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.114Z TRACE 2020-08-14 16:33:57.114 [Thread-226] de.intranda.olr.queue.ProcessingRequestExecutor.newTaskFor(ProcessingRequestExecutor.java:40)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.114Z         Adding to Queue at position 0: Processing IMAGESAVER on 1625_b19371469_0002.tif	 Status: INITIALIZED
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.115Z WARN  2020-08-14 16:33:57.115 [Thread-226] de.intranda.olr.LayoutManager.saveImageWithTimeout(LayoutManager.java:746)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.115Z         Interrupted exception for image 328030/images/master_ms_1625_b19371469_media/1625_b19371469_0002.tif
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.115Z java.lang.InterruptedException: null
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.115Z 	at de.intranda.olr.LayoutManager.saveImageWithTimeout(LayoutManager.java:719) ~[LayoutWizzard-jar-with-dependencies.jar:?]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.115Z 	at de.intranda.olr.LayoutManager.lambda$saveSelectedImages$1(LayoutManager.java:675) ~[LayoutWizzard-jar-with-dependencies.jar:?]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.115Z 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.115Z DEBUG 2020-08-14 16:33:57.115 [Thread-226] de.intranda.olr.LayoutManager.lambda$saveSelectedImages$1(LayoutManager.java:686)
> ecs/workflow-stage-goobi workflow-stage-goobi/workflow-stage-goobi/f714c26e-53ec-41a2-9557-3ee271377da1 2020-08-14T15:33:57.115Z         Done processing all images
>

**Comment by aray-wellcome** [comment]
Unsure if this is still a problem. It's likely not as a lot of work has gone into LW since August. Closing this now and we'll open a new issue if we get an error.
