### ISSUE TITLE
Add Fargate service with Goobi worker node + SQS

### ISSUE THREAD

**Issue by opaetzel** [wellcomecollection/goobi-infrastructure#325]
This means

- [x] add SQS to staging terraform
- [x] add fargate service for Goobi worker node
- [x] change staging Goobi workflow configuration for use of worker node
- [x] testing of all currently available job types from Goobi workflow

**Comment by mgeerdsen** [comment]
A node has been deployed and tested for different job types on staging. Separate issues have been opened for bugs and enhancements. So this one can now be closed.
