### ISSUE TITLE
Update the METS with Wellcome Collection info

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#329]
![image](https://user-images.githubusercontent.com/49983203/93572850-57af4d00-f98e-11ea-97e4-b555bc62fd38.png)

- [ ] dv:ownerContact should be changed to digital@wellcome.org

- [ ] dv:ownerSiteURL should be updated to http://wellcomecollection.org

- [ ] dv:ownerLogo should be changed from a Wellcome Library logo to a Wellcome Collection logo
(Clarification question first: This logo isn't currently used by DDS to display a logo on the Universal Viewer. DDS picks up a different logo that's not in the METS to display. Do you have any insight into how this logo is used in the METS? I don't want to change it to the WC logo yet if it displays anywhere)

**Comment by rsehr** [comment]
all information can be changed in the project configuration. As far as I know the logo is used when you open a mets file in dfg-viewer.de
As your mets file will not work there and you don't use the image in the DDS, you could leave the field blank - or add the uri to the image the dds uses

**Comment by aray-wellcome** [comment]
Thanks for the clarification @rsehr I didn't think we used it anywhere but Tom Crane suggested we might leave it in for API reasons. The logo DDS is using is this one https://github.com/wellcomecollection/iiif-builder/blob/master/src/Wellcome.Dds/Wellcome.Dds.Server/wwwroot/logos/wellcome-collection-black.png

Is there a way to bulk update the projects' configurations or shall I do them manually?

**Comment by rsehr** [comment]
We can change it for all projects in the database, no need to change it manually in the UI for each project. 

But I would prefer to link to the url the DDS uses instead of the github version of it

**Comment by aray-wellcome** [comment]
I checked with Digirati and they are going to be using this URL https://iiif.wellcomecollection.org/logos/wellcome-collection-black.png for the logo but it's not there yet.

**Comment by rsehr** [comment]
I have changed the project configuration on both systems

**Comment by aray-wellcome** [comment]
I have checked the METS produced in staging and prod and confirm it has the new wellcome.org information on it. Thanks Robert!
