### ISSUE TITLE
Bulk MarcXML upload not working (staging & prod)

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#330]
We have been unable to upload marcXMLs in zip files in both staging and production Goobi though individual uploads still work. 

**Expected behavior:**

1. Go to process templates, select JP2_Manual_Edit_METS with Archives Digitisation as the project
2. Choose File Import Upload tab
3. Choose the plugin_import_fileupload_wellcome from the drop down menu
4. Click Choose File and navigate to processed_files.zip on hard drive
5. Click Save
6. GoobiScript activates and creates 34 processes

**Current behavior:**
1. Go to process templates, select JP2_Manual_Edit_METS with Archives Digitisation as the project
2. Choose File Import Upload tab
3. Choose the plugin_import_fileupload_wellcome from the drop down menu
4. Click Choose File and navigate to processed_files.zip on hard drive
5. Click Save
6. A 100% status bar is generated across the screen and completes but
7. GoobiScript is not activated and
8. The 34 are not created

There is no error message either on production or staging Goobi to indicate what error has occurred. 

However, a 504 gateway timeout screen did appear in production Goobi after I clicked save and left it for sometime

I have attached the exact zip file to test with for you. 

[processed_files.zip](https://github.com/wellcomecollection/goobi-infrastructure/files/5260129/processed_files.zip)

**Comment by rsehr** [comment]
I found and fixed the issue. It is already installed on the staging system. 

The reason for this is that you files start with '.', which means in the linux world that it is a hidden file. For another customer we had to ignore problematic files like thumbs_db or hidden files from our default folder listing method. Therefore all xml files where skipped when the zip was read. I implemented a separate method for the import where hidden files are allowed.

**Comment by aray-wellcome** [comment]
Oh that makes complete sense! I'm not sure why Branwen's files are exported from sierra with the . in front of them. Just to clarify though, is the exception you made just for the marcXML upload?

I know we've had to have the S3 ingest ignore the macosx hidden files and stuff so I wouldn't want this to conflict.

**Comment by rsehr** [comment]
yes, the exception is only used for the marc import

**Comment by aray-wellcome** [comment]
Nice! Ok. I've just tried to import the process_files.zip attached to this page. The 34 items were successful and then, I think they tried to run again so I have 34 unsuccessful. I think it was user error because Branwen has tested a few small zips without any errors so I think this is working now. I think we can deploy to prod.

**Comment by rsehr** [comment]
We need to deploy a new goobi container to install it. This results in ~15 min downtime.

When is a good time to do this?

**Comment by aray-wellcome** [comment]
I'm the only one in Goobi at the moment and heading for lunch soon. We could do it now or later this afternoon when you're ready?

**Comment by rsehr** [comment]
I have installed the update, Goobi is up and running again

**Comment by aray-wellcome** [comment]
Great, thanks! I have let Branwen know and she'll add her marcXMLs sometime soon and let me know.

**Comment by aray-wellcome** [comment]
Branwen has been able to upload a zip of marcXMLs on prod Goobi as expected.
