### ISSUE TITLE
Reports of slowness and 504 gateway timeouts messages in prod Goobi

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#331]
Users are reporting slowness in Goobi this week mainly when:

- Searching for a bnumber
- Going to the process templates
- Going to My Tasks
- Entering Edit METS

**An example:**

Searching b16695525_0001 takes ~20 seconds to load the search result. Clicking the Edit METS button sometimes takes ~20 seconds to load or much longer, ending in a 504 gateway time out message

**Comment by mgeerdsen** [comment]
There is a chance that this is EFS related as well. We will have to oberserve the performance in different areas a bit probably. It might also be good to use a different EFS instance for Goobi metadata and not share it with working storage for the ITM/shell server tasks.

**Comment by aray-wellcome** [comment]
Closing this ticket as this issue is dealt with at the time of occurrence (intermittent) in Slack and has no one cause yet. Will open a new one if necessary.
