### ISSUE TITLE
Audio S3 Upload change for new workflow (staging Goobi)

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#332]
When testing the new audio workflow in staging Goobi, I need to download the audio files from an S3 bucket, zip them on my hard drive, and upload them again to workflow-stage-upload. 

We would like to be able to keep all audio files in the Cloud when ingesting in Goobi like we do for the films. In the film workflow, a folder with the process name is created under the A/V section and the appropriate files are placed in there via a S3 copy from another bucket. 

This works for the film workflow because the Lambda knows to wait for:
1. One MXF, one MP4, one JPG (and maybe a PDF transcript)
2. One MPG, one JPG (and maybe  PDF transcript)

But the audio workflow is harder to pin down in terms of what the Lambda should expect because there's no set hard rule of what files will be uploaded for a given item. File combinations could include:
1. One or multiple WAV files and maybe a PDF transcript and/or a JPG poster image
2. One or multiple MP3 files and maybe a PDF transcript and/or a JPG poster image

So we cannot rely on the Lambda to trigger the ingest for us but is it possible for us to:
1. Create a folder with the process name in the A/V folder (or just an audio folder) in the workflow-stage-upload bucket
2. Move all files for an item via S3 copy into the folder on workflow-stage-upload bucket from another bucket
3. Manually trigger the ingest from workflow-stage-upload once all files needed are present (by something in Goobi, perhaps?)
4. The files continue in the new audio workflow as expected

**Comment by mgeerdsen** [comment]
Indeed that should work and we would like to implement it that way.

We would change the current av prefix to separate audio and video prefixes and implement a way to mark the ingest as complete in Goobi.

Actually the logic behind all these ingest mechanisms is part of Goobi, the different lambda functions trigger with each uploaded file and the function then triggers a matching endpoint in Goobi which handles the rest (check for a complete video upload etc.)

**Comment by mgeerdsen** [comment]
Changes for lambda and s3 triggers etc. can be found in PR #339 and have been deployed to staging. Therefore the av prefix is not used anymore, but audio and video should.

**Comment by mgeerdsen** [comment]
infrastructure has been adapted via PR #339

**Comment by aray-wellcome** [comment]
If we could change the behavior in the bucket that causes the bnumber folder to disappear under /video when you upload one file to it, we can close this. The bnumber folder should persist to allow multiple copies to it without needing to recreate it.

**Comment by aray-wellcome** [comment]
Closing this and opening #346
