### ISSUE TITLE
Parsing A/V METS' duration and width, height

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#333]
It is understood that Goobi copies the id3 tag/exif metadata for a video or audio file to create technical metadata information in the METS for duration (both video and audio) and width, height (video). 

DDS needs to read this technical information now in order to create the IIIF. However, the duration and width, height formats in the METS are not consistent. For example: 

The MPG:

          <premis:significantPropertiesType>Duration</premis:significantPropertiesType>
          <premis:significantPropertiesValue>12mn 56s</premis:significantPropertiesValue>

          <premis:significantPropertiesType>ImageWidth</premis:significantPropertiesType>
          <premis:significantPropertiesValue>2048</premis:significantPropertiesValue>

          <premis:significantPropertiesType>ImageHeight</premis:significantPropertiesType>
          <premis:significantPropertiesValue>2048</premis:significantPropertiesValue>
The MXF:

          <premis:significantPropertiesType>Duration</premis:significantPropertiesType>
          <premis:significantPropertiesValue>12 min 56 s</premis:significantPropertiesValue>

          <premis:significantPropertiesType>ImageWidth</premis:significantPropertiesType>
          <premis:significantPropertiesValue>2 048 pixels</premis:significantPropertiesValue>

          <premis:significantPropertiesType>ImageHeight</premis:significantPropertiesType>
          <premis:significantPropertiesValue>2 048 pixels</premis:significantPropertiesValue>

DDS will likely be able to parse these values for its own purposes but Digirati believe it's best practice to just have it read directly from the METS if possible. 

Is Goobi able to parse the id3 tag/exif metadata into standard formats when copying and writing these values to the METS?

Duration would be best in unix time and the width and height would just be integers rather than strings (and without spaces).

**Comment by aray-wellcome** [comment]
I asked Tom Crane about any parser mapping for the different durations, width and heights and this is what I got:

> I know we spoke about Goobi parsing the width, height, duration in the METS if it can but DDS can do it if we can't get it to work. Do you have any sort of mapping from your parser on the different formats you need to clean up? Wondering if Intranda can have a look to get them started and covering the same bases
> 
> tomcrane  12:33 PM
> Hi @ashleyray
> I'm afraid our "parser" is just this at the moment:
> 12:33
> https://github.com/wellcomecollection/iiif-builder/blob/0d67feab8043d0f284a24a49da71625f32cf9f7e/src/Wellcome.Dds/Wellcome.Dds.AssetDomainRepositories/Mets/Model/PremisMetadata.cs#L70
> 
> 12:34
> We haven't yet collected a rogues gallery of variant formats. What I was probably going to do there, when we get to it, is do a sweep of all the AV and collect all the duration strings into a file so we can have a look at it.
> 
> Ashley Ray (she/her)  12:35 PM
> Ahh ok, was hoping you had all the rogues identified! Well, I'll let Intranda know. Where would you sweep the av collection, in DDS?
> 
> tomcrane  12:36 PM
> No from the METS - using a list generated by DLCS though.
> 
> Ashley Ray (she/her)  12:36 PM
> Gotcha
> 
> tomcrane  12:37 PM
> sorry, DDS
> 12:37
> sorry, iiif-builder
> 12:40
> There are several parts to this that have now fallen into place. We can use the catalogue API dumps to generate tasks based on lists of b numbers for the DDS to process. One of those tasks could be to generate AV b numbers. Another task takes this list and reads duration data. We end up with something like
> b12345678 | 2mins 5 seconds
> b23121212 | 00:34
> b78778887 | around half an hour or so
> 12:40
> and so on
> 12:40
> I hope we don't get too many like the last...
> 12:41
> At least we can then see what our parser has to content with, and then make sure it at least makes a success of all these known examples
> 
> tomcrane  12:46 PM
> The other approach would be to actually measure the duration of the binary file. This would be safer but I think that approach may have been rejected?
> 12:47
> (This also seems like a problem multiple people have solved before)
> 
> Ashley Ray (she/her)  12:48 PM
> That's good information! I'll pass that on to Intranda and see if we can get Goobi parsing
> 
>

**Comment by aray-wellcome** [comment]
I've tested film b3216273x on staging and the METS is now showing duration in milliseconds and width/height as numbers only. However, the width is being copied as the height as well in the METS. 

The METS says:
![image](https://user-images.githubusercontent.com/49983203/99543244-e1898f80-29aa-11eb-94cb-8cca8a507436.png)

While MediaInfo online run manually says:

![image](https://user-images.githubusercontent.com/49983203/99543316-f534f600-29aa-11eb-8885-362e0dc6d75f.png)

Can we get the height written to the METS accurately?

Also, the milliseconds is written as 468.292 but if I convert that with the decimal, it's wrong. If I take out the decimal then the time is converted to 7 min 48 s which is correct. Is it supposed to have the decimal in it?

**Comment by rsehr** [comment]
The height is corrected now. 
The duration is stored as the requested unix time, which is measured in seconds. So the stored value is 468 sec, 292 ms, this can be converted into 7,80486667 min or 7 min, 48s, 292 ms.
We can change it and store the value as ms only, or we can remove the ms and store only the seconds or we can use another delimiter. It depends on what Digirati wants. Internally we have ms, it can be converted into any format they want.

**Comment by aray-wellcome** [comment]
Awesome, just testing the h/w now. And thanks for explaining the unix time stuff, more just me and Harkiran being unfamiliar than anything else!

**Comment by aray-wellcome** [comment]
Re-ran the film and the METS has the height correct now so I'm going to close this. If we need any other adjustments after speaking to Digirati, I'll open a new ticket. 

![image](https://user-images.githubusercontent.com/49983203/99777982-fb41e880-2b0a-11eb-8ea0-06e9c5a49836.png)
