### ISSUE TITLE
Editorial Photography Shoots Progressing Slowly

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#334]
A photographer uploaded EP_001404 through FZP to the editorial/workflow-upload bucket on 21 Sept around noon. The zip was ~10gb. When it did not show up in TandemVault by this afternoon (22 Sept, 15:00) he asked me to check on it. 

I can see from the process time stamps that the process was not created until 3:28am 22 Sept) and the next step, Embed Metadata, was not automatically triggered until 14:00 22 Sept.

Also, he uploaded EP_001415 around 14:00, that was created by 14:43 but when I checked at 15:06, the Embed Metadata step was still on open/orange. I manually triggered the next step to see if it would move along and it did. 

**Expected behavior**
The process would create within minutes of being ingested from the editorial/workflow-upload bucket and progress along the steps in a timely manner and arrive in Tandem Vault within a few hours, maybe more with the large size

**Current behavior**
The process was uploaded to the bucket and wasn't created for ~12 hours. The next step in the workflow was not automatically triggered until ~11 hours after that. It is currently in the TIFF Validation step

**Comment by mgeerdsen** [comment]
Not sure if this is still a problem. This could also be EFS related.
I'll try to check on EP tasks on Monday to see if this is still relevant currently

**Comment by mgeerdsen** [comment]
Having checked the timing of the processes and the single steps in these workflows, I am pretty sure that this is related to EFS performance issues. Many of the steps make use of EFS as temporary working storage.

With the recent changes we should observe the future behaviour and revisit this when needed. Though we should investigate the use of different EFS mounts for different things or ephemeral storage on Fargate for a few tasks in the future.
