### ISSUE TITLE
Some bags are failing to be put into wellcomecollection-workflow-export-bagit

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#336]
There has been an intermittent problem with bags failing to be added to wellcomecollection-workflow-export-bagit. This was hard to investigate due to other BagIt issues. The memory problems with BagIt seem to be resolved but the issue is continuing to happen.

**Two examples from Prod Goobi:** 
b14584463_0001
b13154606_0001

Both have been through BagIt at least once this week. No error messages occurred at the BagIt Step. 

When at the Send ingest request to archive service step, it fails with the message: Received callback request from archive service. Status is 'failed'.

Taking the UUID and going to the ingest inspector, the error message "Unpacking failed - Error reading s3://wellcomecollection-workflow-export-bagit/b13154606.tar.gz: either it doesn't exist, or the unpacker doesn't have permission to read it" is present.

https://wellcome-ingest-inspector.glitch.me/ingests/b7284b3e-dd90-4c03-986e-f8a804aef2b7
https://wellcome-ingest-inspector.glitch.me/ingests/2a4582b5-1570-4c93-9132-527e34d2e6aa

Having had the same issue on Monday with four other items, I know that the log has been showing that the items were created and uploaded to the bucket https://wellcome.slack.com/archives/C6LLC2V8Q/p1601284836015000

But when I've asked Alex to look into the bucket, they could not find the bags. 

It seems that the bags are either not being created or not being placed in the bucket but the log is reporting that they have. There is no error detected until the storage service tries to retrieve the bag.

**Comment by rsehr** [comment]
we have updated the bagit creation. The bagit creation and upload step will end in an error, If the upload to the bucket fails. Also we should have a detailed error message, why it failed sometimes.

I restarted both processes. b14584463_0001 was successful, b13154606_0001 is still running

**Comment by aray-wellcome** [comment]
There was a Bagit failure on Friday on prod for b10004014_0002 with the error message

> 12:17:10.320 [main] ERROR de.intranda.wellcome_export_bagit.BagitFilesystemManipulator - com.amazonaws.SdkClientException: Unable to complete multi-part upload. Individual part upload failed : Unable to execute HTTP request: Socket is closed
> 12:17:17.686 [main] ERROR de.intranda.wellcome_export_bagit.BagitCoordinator - com.amazonaws.SdkClientException: Unable to complete multi-part upload. Individual part upload failed : Unable to execute HTTP request: Socket is closed

**Comment by aray-wellcome** [comment]
No further issues have happened in the last 2 weeks. Closing and will open a new ticket if something else occurs.
