### ISSUE TITLE
Files failing to be copied from S3 upload bucket to EFS in import

### ISSUE THREAD

**Issue by mgeerdsen** [wellcomecollection/goobi-infrastructure#338]
We are experiencing problems when downloading zip files from the upload S3 bucket to temporary space on EFS.

**Comment by mgeerdsen** [comment]
this might or might not be related to #336

**Comment by mgeerdsen** [comment]
For #336 we observed the following error occasionally when uploading from efs to s3:

> ERROR de.intranda.wellcome_export_bagit.BagitFilesystemManipulator - com.amazonaws.SdkClientException: Unable to complete multi-part upload. Individual part upload failed : Unable to execute HTTP request: Socket is closed


For downloads from s3 in to efs in goobi we have occasionally observed:

> ERROR (DownloadS3Handler.java:68) - com.amazonaws.SdkClientException: Unable to complete multipart download. Individual part download failed.

or this combination:

> ERROR (DownloadS3Handler.java:68) - com.amazonaws.SdkClientException: Unable to complete multipart download. Individual part download failed.
> WARN  (S3AbortableInputStream.java:178) - Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
> 

Also this could be observed for a period of time, but did come up again so far:

> com.amazonaws.services.s3.transfer.exception.FileLockException: Fail to lock /efs/tmp_goobi/5ef071ba-dcbe-4384-8de2-1368d919ef1d/b19595633.zip

**Comment by mgeerdsen** [comment]
shellserver instances have increased CPU and memory settings

staging goobi has parallel downloads disabled... still observing

**Comment by aray-wellcome** [comment]
No further issues have happened in the last 2 weeks. Closing and will open a new ticket if something else occurs.
