### ISSUE TITLE
Change film ingest from S3 to have manual step like audio ingest

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#346]
workflow-stage-upload/film/bnumber folder disappears when a file is copied to it, forcing us to create the bnumber folder two or three times for an ingest. 

It'd be helpful if the bnumber folder could be created and then remain so all three separate files could be copied to it without having to create it over and over

Closing #332 for this issue

**Comment by aray-wellcome** [comment]
Related, the Goobi workflow moves forward before we can get all the files in. Usually the PDF doesn't make it and we have to roll it back. Is there an order to get the files in before Goobi moves forward?

**Comment by aray-wellcome** [comment]
To help the issue above, maybe we could change the film ingest to be like the audio, in which we can load the files from S3 and then pick up the task, check what's in there and release? We're having a hard time keep track of what we put in for films. 

How much work is that? We'd like to try it on staging at least.

**Comment by opaetzel** [comment]
We will change the film ingest to be like the audio and delete the prefix/folder only after the manual step is closed. This will take approx 2 days.

**Comment by aray-wellcome** [comment]
Yeah, let's go for it! Harkiran and I have discovered while testing this week that it's way to easy to get distracted and remember what you put in haha
