### ISSUE TITLE
Change EP CSV requirements in Goobi

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#351]
There was an EP item failing due to a column on the ingest csv being named Freelancer rather than Freelance Photog. 

This change was made in LightBlue by the photographers who want to continue using Freelancer on the csv exports. Can we change Goobi's config to accept Freelancer rather than Freelance Photog?

**Comment by opaetzel** [comment]
I guess we should allow both versions, for updates of older shoots?

**Comment by aray-wellcome** [comment]
Ah yeah, that makes sense to allow both, actually! I also told the photographers to let me know before they change a field again.

**Comment by opaetzel** [comment]
We'll need to update Goobi production for this change

**Comment by aray-wellcome** [comment]
Ok! You can probably do it first thing in the morning if you would like?
