### ISSUE TITLE
Add Open with Advisory to Access

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#358]
![image](https://user-images.githubusercontent.com/49983203/104929800-4443db00-599c-11eb-951e-e2dfd5f20969.png)

On the Access Status drop down menu in Edit METS, could you please add a new Access Status: Open with Advisory

On the METS file, it should map to the following:

`<mods:accessCondition type="status">Open with advisory</mods:accessCondition>`

Moving forward, Open with advisory will be used for new ingests rather than requires registration. Requires registration will still appear on the drop down menu for all previously ingested items under that status. 

Digirati will be making a change to the text used for requires registration so it appears as Open with Advisory text if either open with advisory or requires registration is found in the METs. The change is scheduled to be made at the end of the w/c 18 Jan 2021.

**Comment by rsehr** [comment]
We added the new value to the dropdown list. Also it is the new default values in all project that had Requires registration as default before.

**Comment by mgeerdsen** [comment]
appears to have been closed (moved to done) in January
