### ISSUE TITLE
Prod A/V projects should have default copyright and access licenses

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#360]
When we move the new a/v workflows to prod Goobi, we will need the film and audio projects to have the following default copyright and access licenses:

Access License : In copyright
Access Status: Restricted files

**Comment by rsehr** [comment]
I set the new defaults to the Wellcome_Audio and Wellcome_Film project

**Comment by aray-wellcome** [comment]
It looks like In Copyright got put onto the Access Status drop down after this, in both prod and stage 

![image](https://user-images.githubusercontent.com/49983203/106746078-ee1c9c00-6619-11eb-8652-e9568d059492.png)

**Comment by mgeerdsen** [comment]
should be resolved by now
