### ISSUE TITLE
Extend dashboard to show step history

### ISSUE THREAD

**Issue by rsehr** [wellcomecollection/goobi-infrastructure#361]

**Comment by aray-wellcome** [comment]
Is it possible to have a "in process column" as well as the "finished" column? 

Can we get rid of "recent imports" and put the step monitoring boxes in that space instead?

How does the finished steps box win again? It might be that we don't have a lot going through staging so it's not got a lot to show but it feels like nothing much has changed on it.

**Comment by aray-wellcome** [comment]
Ok I think I have a good example of this. 

Take LayoutWizzard auto analysis. At the moment it tells me 1 item has completed that step in the last 7 days
![image](https://user-images.githubusercontent.com/49983203/109957866-6e97f080-7cdd-11eb-8bd1-2e8ca79b4caf.png)

If I click on it, it shows me ms_928 that's already online. That's fine. But I know ms_4048 is currently in auto analysis. If I want to find ms_4048, I have to click on Image Upload finished processes (as that's the step just before auto analysis) on the dashboard and there I can see it's in process at auto analysis. It'd be good to be able to click to see what's currently going through auto analysis.
