### ISSUE TITLE
Move new a/v workflow to production Goobi

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#363]
As DDS can now handle the new METS files for film, it is time to move the new film and audio workflows created on Staging Goobi to Prod Goobi. (Note: audio does not work yet on DDS but I believe we said it makes sense to move everything together)

It would be good to get a checklist on this ticket of all the steps or things necessary to move to prod. 

As part of that list, Harkiran has asked me to make the following small changes as well:

- [x] Remove deactivated steps from both new film and audio workflow on Prod
- [x] Rename Wellcome Film and Wellcome Audio projects current on prod to Wellcome Film (pre-2020) and Wellcome Audio (pre-2020)
- [x] Move all processes currently under Wellcome Film and Wellcome Audio projects to Wellcome Film (pre-2020) and Wellcome Audio (pre-2020)
- [x] Create new Wellcome Film and Wellcome Audio project on Prod the access license `in copyright` and status as `restricted'

**Comment by mgeerdsen** [comment]
also needed (not yet complete)

- [ ] Update Goobi container on production
- [ ] Update shellserver containers on production

@rsehr anything else? configuration? ruleset?

**Comment by rsehr** [comment]
- [ ] Configure filegroups in audio project for OBJECTS, POSTER, TRANSCRIPT (see stage system)
- [ ] update json body for bagit creation and upload in audio worklflow (see stage system)
- [ ] Add new task to both process templates:

Title: Move files
Order: 25
Automatic task: true
Step plugin: intranda_step_movevideofiles / intranda_step_moveaudiofiles
User group: AutomaticTasks

**Comment by aray-wellcome** [comment]
- [ ] Ashley Ray  11:36 AM
I need to do a bulk delete to clean up old film processes on prod we don't want anymore but I'm hesitant to use the Goobiscript and try it haha can we get these deleted when you guys have a chance?
"id:292040 292042 292043 292021 292022 292023 292024 292027 292028 292029 292031 292034 292035 292044 282969 282970 282974 282975 282976 282980 282981 282982 282983 282985 282987 282988 315759 315760 315761 315762 315763 315764 315765 315766 315767 315768 315769 315770 315771 315772 315773 315774 315775 315776 315777 315778 315779 315780 315781 315782 315783 315784 315785 315786 315787 315789 315790 315791 315793 315794 315795 315796 315797 315798 315799 315801 315802 315803 315804 315805 315806 315807 315808 315809 315810 315811 315812 315813 315814 315815 315816 315817 315818 315819 315820 315821 315822 315823 315824 315825 315826 315827 315828 316051 316052 "

**Comment by opaetzel** [comment]
I deleted the old film processes.

**Comment by aray-wellcome** [comment]
Things have been working fairly well. Let's close this and open up a new ticket for any other issues that might pop up.
