### ISSUE TITLE
Delete ingested Proqest MMs for BagIt error clean up

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#367]
We are looking at recent Proquest errors that need cleaned up. We've once again run into the BagIt error issue (Exception in thread "main" java.lang.NumberFormatException: For input string: "hin-wel-all-00001102"). I've written this issue up so as a reminder, this is the reason we have the error:

> One or more parts of the multiple manifestation were ingested prior to migration and the file names were not renamed from the bnumber_hin_wel_all-00000XXX_000X.jp2 format, which does not specify which manifestation these files belong to. This file name type was acceptable in Preservica but the storage service requires files to be renamed into the bnumber_000X_000X.jp2 format, which does specify the manifestation, right after the bnumber. 
>  When ingesting another MM item, the BagIt tool looks up for already existing manifestations in order to create a fetch file for all files that are not updated by the current manifestation. Because the file name format bnumber_hin_wel_all-00000XXX_000X.jp2 does not have the manifestation order number, the BagIt tool doesn't know which files belongs to which manifestation and therefore, cannot ingest the new item.  

We can't delete these through the Delete bnumber plugin ourselves as we run into the same BagIt Error. The solution has been to:

> Deleting the bnumber from the Storage Service using the Delete bnumber plugin itself will not work due to the same reasons as above: the BagIt tool doesn't know which files belongs to which manifestation and therefore cannot bag the item. Instead, ask Intranda to delete the item via the plugin and manipulate the task BagIt creation and upload by adding a parameter "purge":true to the json.

Can we please "delete" these items from the storage service so we can get everything fixed and ingested? 

b12947696_0002
b12947696_0004
b12947696_0005
b1313629x_0001
b13149040_0002
b13149040_0005
b10004300_0002
b10005614_0001
b10916441_0001
b11533353_0001
b11533353_0003
b12201777_0002
b12645163_0001
b12838767_0001
b12946448_0002
b1294662x_0001
b12946795_0002
b12948457_0001
b10326273_0002

**Comment by aray-wellcome** [comment]
"project:SampleProject" "stepopen:automatic MMO archive status check" I've started the delete from storage service process for these now

**Comment by aray-wellcome** [comment]
These have all had a deletion task started for them now.

**Comment by aray-wellcome** [comment]
We have a few more to finish up this work that was left off the previous list: 
b11533353_0001 
b11533353_0002
b12181110_0002
b10005614_0001

**Comment by rsehr** [comment]
all b-numbers are deleted
