### ISSUE TITLE
Add workflowupload@wellcome.org to Lambda event notifications

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#387]
Add workflowupload@wellcome.org to workflow-upload and workflow-stage-upload bucket Lambda event notifications so that any time an item is uploaded into the bucket, we receive an email.

**Comment by mgeerdsen** [comment]
This should probably be implemented by adding an SNS topic which receives event notifications from S3. The mail could then be send via SNS.
