### ISSUE TITLE
Lurawave conversion gets stuck and errors

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#406]
Items that go through Lurawave conversion in SQS are not reporting back that the images are finished converting. 

I can look at the item's files and tell that the conversion is complete and manually move it a long. There's currently an error message that will pop up after some time (maybe ~24hours?) that says:

<html>
<body>

Aug 1, 2021 5:28:25 PMGoobi DLQ listener | Script ticket failed after retries
-- | --

</body>
</html>

At first I thought this was only happening to very large items but it's also happening to small items of ~150 files. 

I've given a few examples before but here's a recent one pp_ami_d_196_b32501638

**Comment by opaetzel** [comment]
This seems to be resolved. I tested on staging yesterday and got a process through lurawave and Ashley tested in production and it worked there, too.
