### ISSUE TITLE
OGL and CC-BY Licenses for IA items not being mapped to correct license

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#412]
Recently, we've been digitizing items in Internet archive that have an Open Government License or are CC-BY but these licenses aren't being mapped correctly in Goobi, which is causing problems downstream for our catalogue pipeline. 

**Open Government License**
Examples: b32222622, b32222415, b32219301, b32218898, b32219295, b32220510, b32218953, b32220790, b32219635, b32220376

These items are supposed to have an Open Government License. In Goobi, at Edit METS, these are mapped to CC-0 rather than OGL. In the METS it's displaying the OGL URL rather than a license code. 
![image](https://user-images.githubusercontent.com/49983203/139397472-0a82ed78-e530-4b24-8f75-d3a873885330.png)

**CC-BY**
Example: b32174305

This item is supposed to have a CC-BY license but it's being again mapped to CC-0 in Goobi and it's displaying the CC-BY URL rather than the CC-BY license code. 
![image](https://user-images.githubusercontent.com/49983203/139398315-b092c7b0-1b88-47bc-a186-322ba294ec65.png)

Can we please fix this so these types of licenses are being mapped correctly in Goobi? And can we fix all of the IA items that haven't been mapped correctly? I think that they are probably going to be just from Oct 28th's import.

**Comment by aray-wellcome** [comment]
These are now mapped correctly

**Comment by aray-wellcome** [comment]
This seems to be an issue again. About 200 items came through from IA on 28 June with www.nationalarchives.gov.uk/doc/open-government-licence/version/3 and were not mapped to an OGL license. 

Can we get this remapped? I should be able to fix the ones that came through wrong via Goobiscript. 

It might be worth checking the CC-BY is still going to be mapped correctly from the URL as well.

**Comment by rsehr** [comment]
Can you give me an example record where its wrong?

**Comment by aray-wellcome** [comment]
Yeah! I'm doing a Goobiscript to fix them already though, oops. b32226494

I do have a search for them though that shows what was in the AccessLicense space instead of OGL
![image](https://user-images.githubusercontent.com/49983203/177273449-c8bbb5fb-8a61-4519-86b1-10b09d2edb3c.png)

**Comment by rsehr** [comment]
b32226494 has the license data, the IA provides:
https://ia902508.us.archive.org/14/items/b32226494/b32226494_meta.xml

Here you can see the line 
<rights>&lt;a href="http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" rel="nofollow"&gt;You have permission to make copies of this work under an Open Government license.&lt;/a&gt;</rights>

**Comment by aray-wellcome** [comment]
Yeah that license data is correct but it should map to the OGL license, not just the URL www.nationalarchives.gov.uk/doc/open-government-licence/version/3/ in the METS. Our system doesn't know what to do with the URL so it causes an error in the METS transformer 

![image](https://user-images.githubusercontent.com/49983203/177274292-c55069f0-4eac-4ff6-863b-82f2567a7c54.png)
