### ISSUE TITLE
expand deletion step

### ISSUE THREAD

**Issue by mgeerdsen** [wellcomecollection/goobi-infrastructure#416]
We should expand the existing deletion step, to also remove the following:

- the source directory/prefix of a process which contains the downloaded IA files
- the contents of the ocr prefix (which contains OCR files like ALTO files for IA processes or from older OCR processing)

We should also discuss if this should only happen for harvested material (19c/MOH) or for all processes.

**Comment by aray-wellcome** [comment]
Christy is checking on some old emails to see if there was a decision made long ago about saving jpgs for archival items or not (because we have January openings for archival items so it's easier to do them if the jpgs are still there). But the IA files seem like the best place to start so far.

**Comment by mgeerdsen** [comment]
Robert checked and the deletion step does delete the source prefix and the ocr prefix as mentioned above.

The JP2_Auto_Edit_METS workflow appears to have jpeg deletion disabled, I am not sure if this should stay this way. @aray-wellcome ?

**Comment by aray-wellcome** [comment]
I remember shutting off jpg creation for the auto edit mets workflow because humans don't look at Edit METs and it was wasting resources...I think we can keep it off.
