### ISSUE TITLE
BagIt Timeout error

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#418]
Several large items are failing at BagIt due to a timeout error

`error in script 'Script 1':

called: /usr/bin/java -jar /usr/local/bin/wellcome-export-bagit.jar --goobiID 275755 --title Opera medica in quatuor tomos divisa / --bnumber b10336795 --goobiTitle 28475_d_b10336795 --metsFile /opt/digiverso/goobi/metadata/275755/28475_d_b10336795.xml --anchorFile /opt/digiverso/goobi/metadata/275755/28475_d_b10336795_anchor.xml --s3PrefixAlto 275755/ocr/28475_d_b10336795_alto --s3PrefixImages 275755/images/28475_d_b10336795_media/ --outputBucket wellcomecollection-workflow-export-bagit --archiveType tar.gz

Command timed out after 42900 seconds.`

Example: b10336795

The items are generally 900-1500 jp2s so may be too big for our working storage

**Comment by mgeerdsen** [comment]
We are using a shared EFS instance for all worker nodes if the size of a process exceeds a limit of several GB and cannot be handled on ephemeral storage. During high volume periods this result in EFS bandwith being limited, which is probably the root of this timeout error.
There are several options that we are currently discussing. Including switching to guaranteed EFS bandwith or adding more ephemeral storage to the nodes (which was originally not available).

**Comment by mgeerdsen** [comment]
This should be adressed via #426
