### ISSUE TITLE
BagIt Error: No Space Left on Device

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#421]
Proquest items have been getting this error recently. Example for b10335857

error in script 'Script 1':

called: /usr/bin/java -jar /usr/local/bin/wellcome-export-bagit.jar --goobiID 280700 --title Istorica descrizione de' tre regni Congo, Matamba, et Angola ... e delle missioni apostoliche esercitatevi da religiosi Capuccini ... / --bnumber b10335857 --goobiTitle 17116_c_b10335857 --metsFile /opt/digiverso/goobi/metadata/280700/17116_c_b10335857.xml --anchorFile /opt/digiverso/goobi/metadata/280700/17116_c_b10335857_anchor.xml --s3PrefixAlto 280700/ocr/17116_c_b10335857_alto --s3PrefixImages 280700/images/17116_c_b10335857_media/ --outputBucket wellcomecollection-workflow-export-bagit --archiveType tar.gz

return code: 1

stdout: b'WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.\n09:05:34.085 [main] ERROR de.intranda.wellcome_export_bagit.BagitCoordinator - java.io.IOException: No space left on device\n'

stderr: b''

**Comment by mgeerdsen** [comment]
The size threshold to use EFS instead of ephemeral storage has been lowered a bit and the affected processes appear to work fine now.
