### ISSUE TITLE
Bagit: stream zip directly to S3

### ISSUE THREAD

**Issue by opaetzel** [wellcomecollection/goobi-infrastructure#422]
Right now, we are creating a bagit zip file on EFS. The zip file is then uploaded to S3 with a TransferManager, as it might exceed the size limit of 5GB for standard object uploads.
We now want to stream the zip directly to S3, utilizing S3 multipart uploads. For this, we will gather 50 MB chunks of data in a buffer on the heap and compute the md5 of that buffer. Then we will upload that chunk as a part of the multipart upload, setting the md5 sum as the ETag. This will continue until we reach the end of our zip stream. The last chunk may be smaller. 

As the multipart upload allows 10 000 chunks, we can upload bags of up to 500 000 MB (~500GB) with this method.

**Comment by aray-wellcome** [comment]
We are good to go ahead with this 👍
