### ISSUE TITLE
Replace Lurawave with grok for .tiff>.jp2 conversions

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#424]
Luratech is no longer supporting Lurawave and has let us out of our contract. We would like to replace Lurawave with [OpenJPEG](https://github.com/uclouvain/openjpeg/tree/v2.4.0) for our .tiff to .jp2 conversions.

**Comment by aray-wellcome** [comment]
https://wellcome.slack.com/archives/C6LLC2V8Q/p1583237193029900

That link above is where we talked about the Lurawave settings. Pasting below as well:

> config_rate8.xml: c -i $inputFile$ -o $outputFile$ -Part1 -rate 8 -precise -accurate -visual 0 -layers 8 -tilew 1024 -tileh 1024 -tlm -levels 5 -p rpcl
> 12:06
> ist used in
> 12:06
> 3rd Party TIFFs
> Ancestry-JPEGs
> Arabic_Manuscripts
> Archives digitisation
> Borthwick_3rd_Party_ftp
> Digitisation_on_Demand
> General_Manuscripts
> Glasgow_Crichton_3rd_Party_ftp
> LMA_3rd_Party_ftp
> Medieval_Manuscripts
> Paintings
> Recipe_Books
> Visual_Arts
> 12:07
> config_lossless.xml: c -i $inputFile$ -o $outputFile$ -Part1 -layers 8 -tilew 1024 -tileh 1024 -tlm -levels 5 -p rpcl
> 12:07
> is used in Iconographic_Images, Paintings
> 12:07
> config_rate10.xml: c -i $inputFile$ -o $outputFile$ -Part1 -rate 10 -precise -accurate -visual 0 -layers 8 -tilew 1024 -tileh 1024 -tlm -levels 5 -p rpcl
> 12:07
> is used in Archive Backlog, Archives digitisation, Genetics_Books_Project, Wellcome_Digitisation_Project
> 12:07
> config.xml: c -i $inputFile$ -o $outputFile$ -Part1 -layers 8 -tilew 1024 -tileh 1024 -tlm -levels 5 -p rpcl
> 12:08
> is used in Reading_Room_mini-theme
> 
> Ashley Ray  12:15 PM
> Are those Lurawave settings set on the project? Rather than the process template then?
> 
> Robert Sehr  12:18 PM
> they where on the process templates, the config*.xml is configured in the Lurawave task, but I could not found process templates for all projects any more
>

**Comment by aray-wellcome** [comment]
Also found this online, if at all helpful (but maybe it's old?) https://www.dpconline.org/docs/miscellaneous/events/529-jp2knov2010parametercomparisonchart/file

**Comment by mgeerdsen** [comment]
switched over to grok on both staging and production
